from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.models.project import TECHNOLOGY_TYPES, PROJECT_STAGES, OFFTAKE_TYPES, ENTITY_TYPES
from app.utils.validators import coerce_numeric_fields, validate_project_input
from app.session_store import store_set

project_bp = Blueprint("project", __name__)


SAMPLE_PROJECTS = {
    "solar_100mw": {
        "project_name": "Prairie Sun Solar Farm",
        "project_id": "PSS-2026-001",
        "project_stage": "advanced_development",
        "entity_type": "cooperative",
        "location_state": "Kansas",
        "location_county": "Ford",
        "is_rural": True,
        "description": "100 MW utility-scale solar PV facility serving a rural electric cooperative.",
        "technical": {
            "technology_type": "solar_pv",
            "nameplate_capacity_mw": 100,
            "annual_generation_mwh": 219000,
            "capacity_factor": 0.25,
            "technology_readiness_level": 9,
            "expected_useful_life_years": 30,
            "degradation_rate_annual": 0.005,
            "availability_factor": 0.98,
            "interconnection_voltage_kv": 138,
            "interconnection_status": "agreement_executed",
            "environmental_permits_secured": True,
            "site_control_secured": True,
        },
        "financial": {
            "total_project_cost": 105000000,
            "total_hard_costs": 84000000,
            "total_soft_costs": 10500000,
            "contingency_percent": 0.10,
            "construction_period_months": 18,
            "debt_percent": 0.75,
            "equity_percent": 0.25,
            "interest_rate": 0.050,
            "debt_tenor_years": 25,
            "target_dscr": 1.35,
            "annual_revenue": 10950000,
            "annual_opex": 2100000,
            "annual_opex_escalation": 0.025,
            "revenue_escalation": 0.02,
            "tax_rate": 0.21,
            "itc_percent": 0.30,
            "ptc_per_mwh": 0,
            "depreciation_schedule": "macrs_5",
            "discount_rate": 0.08,
        },
        "credit": {
            "offtake_type": "ppa_fixed",
            "offtake_tenor_years": 25,
            "offtaker_credit_rating": "A-",
            "offtaker_entity_type": "cooperative",
            "revenue_concentration_percent": 1.0,
            "regulatory_stability_rating": "stable",
            "curtailment_risk": "low",
            "counterparty_count": 1,
            "contract_price_per_mwh": 50,
            "has_credit_support": False,
        },
        "structure": {
            "epc_contract_type": "fixed_price_turnkey",
            "epc_contractor_experience": "established",
            "epc_warranty_years": 2,
            "om_contract_type": "full_service",
            "om_contract_tenor_years": 10,
            "insurance_coverage": "comprehensive",
            "performance_guarantee": True,
            "performance_guarantee_level": 0.95,
            "completion_guarantee": True,
            "reserve_accounts_funded": True,
            "debt_service_reserve_months": 6,
            "major_maintenance_reserve": True,
            "step_in_rights": True,
            "assignment_provisions": True,
            "change_of_control_provisions": True,
        },
        "market": {
            "resource_quality": "good",
            "resource_assessment_confidence": "p50",
            "independent_resource_assessment": True,
            "market_price_per_mwh": 45,
            "market_price_trend": "stable",
            "curtailment_history_percent": 0.02,
            "interconnection_certainty": "secured",
            "grid_congestion_risk": "low",
            "competing_projects_in_queue": 3,
            "community_support": "supportive",
            "land_lease_secured": True,
            "land_lease_term_years": 35,
        },
    },
    "wind_150mw": {
        "project_name": "High Plains Wind Center",
        "project_id": "HPW-2026-002",
        "project_stage": "early_development",
        "entity_type": "independent_power_producer",
        "location_state": "Oklahoma",
        "location_county": "Woodward",
        "is_rural": True,
        "description": "150 MW onshore wind project with long-term PPA to regional utility.",
        "technical": {
            "technology_type": "onshore_wind",
            "nameplate_capacity_mw": 150,
            "annual_generation_mwh": 460000,
            "capacity_factor": 0.35,
            "technology_readiness_level": 9,
            "expected_useful_life_years": 25,
            "degradation_rate_annual": 0.003,
            "availability_factor": 0.97,
            "interconnection_voltage_kv": 345,
            "interconnection_status": "study_complete",
            "environmental_permits_secured": False,
            "site_control_secured": True,
        },
        "financial": {
            "total_project_cost": 225000000,
            "total_hard_costs": 180000000,
            "total_soft_costs": 22500000,
            "contingency_percent": 0.10,
            "construction_period_months": 24,
            "debt_percent": 0.65,
            "equity_percent": 0.35,
            "interest_rate": 0.055,
            "debt_tenor_years": 18,
            "target_dscr": 1.40,
            "annual_revenue": 23000000,
            "annual_opex": 5700000,
            "annual_opex_escalation": 0.025,
            "revenue_escalation": 0.02,
            "tax_rate": 0.21,
            "itc_percent": 0,
            "ptc_per_mwh": 27.50,
            "depreciation_schedule": "macrs_5",
            "discount_rate": 0.08,
        },
        "credit": {
            "offtake_type": "ppa_fixed",
            "offtake_tenor_years": 15,
            "offtaker_credit_rating": "BBB+",
            "offtaker_entity_type": "investor_owned_utility",
            "revenue_concentration_percent": 1.0,
            "regulatory_stability_rating": "stable",
            "curtailment_risk": "moderate",
            "counterparty_count": 1,
            "contract_price_per_mwh": 50,
            "has_credit_support": True,
            "credit_support_type": "letter_of_credit",
        },
        "structure": {
            "epc_contract_type": "fixed_price_turnkey",
            "epc_contractor_experience": "established",
            "epc_warranty_years": 2,
            "om_contract_type": "full_service",
            "om_contract_tenor_years": 5,
            "insurance_coverage": "comprehensive",
            "performance_guarantee": True,
            "performance_guarantee_level": 0.95,
            "completion_guarantee": True,
            "reserve_accounts_funded": False,
            "debt_service_reserve_months": 6,
            "major_maintenance_reserve": False,
            "step_in_rights": True,
            "assignment_provisions": True,
            "change_of_control_provisions": True,
        },
        "market": {
            "resource_quality": "excellent",
            "resource_assessment_confidence": "p50",
            "independent_resource_assessment": True,
            "market_price_per_mwh": 42,
            "market_price_trend": "stable",
            "curtailment_history_percent": 0.05,
            "interconnection_certainty": "high",
            "grid_congestion_risk": "moderate",
            "competing_projects_in_queue": 8,
            "community_support": "supportive",
            "land_lease_secured": True,
            "land_lease_term_years": 30,
        },
    },
    "storage_50mw": {
        "project_name": "Valley Grid Storage",
        "project_id": "VGS-2026-003",
        "project_stage": "advanced_development",
        "entity_type": "municipal_utility",
        "location_state": "Arizona",
        "location_county": "Maricopa",
        "is_rural": False,
        "description": "50 MW / 200 MWh battery energy storage system for grid reliability.",
        "technical": {
            "technology_type": "battery_storage",
            "nameplate_capacity_mw": 50,
            "annual_generation_mwh": 73000,
            "capacity_factor": 0.17,
            "technology_readiness_level": 8,
            "expected_useful_life_years": 20,
            "degradation_rate_annual": 0.02,
            "availability_factor": 0.97,
            "interconnection_voltage_kv": 69,
            "interconnection_status": "agreement_executed",
            "environmental_permits_secured": True,
            "site_control_secured": True,
        },
        "financial": {
            "total_project_cost": 65000000,
            "total_hard_costs": 52000000,
            "total_soft_costs": 6500000,
            "contingency_percent": 0.10,
            "construction_period_months": 12,
            "debt_percent": 0.60,
            "equity_percent": 0.40,
            "interest_rate": 0.060,
            "debt_tenor_years": 15,
            "target_dscr": 1.30,
            "annual_revenue": 8500000,
            "annual_opex": 1300000,
            "annual_opex_escalation": 0.025,
            "revenue_escalation": 0.02,
            "tax_rate": 0.0,
            "itc_percent": 0.30,
            "ptc_per_mwh": 0,
            "depreciation_schedule": "macrs_7",
            "discount_rate": 0.07,
        },
        "credit": {
            "offtake_type": "capacity_contract",
            "offtake_tenor_years": 15,
            "offtaker_credit_rating": "AA-",
            "offtaker_entity_type": "municipal_utility",
            "revenue_concentration_percent": 1.0,
            "regulatory_stability_rating": "stable",
            "curtailment_risk": "low",
            "counterparty_count": 1,
            "contract_price_per_mwh": 0,
            "has_credit_support": False,
        },
        "structure": {
            "epc_contract_type": "fixed_price_turnkey",
            "epc_contractor_experience": "established",
            "epc_warranty_years": 2,
            "om_contract_type": "full_service",
            "om_contract_tenor_years": 10,
            "insurance_coverage": "comprehensive",
            "performance_guarantee": True,
            "performance_guarantee_level": 0.95,
            "completion_guarantee": True,
            "reserve_accounts_funded": True,
            "debt_service_reserve_months": 6,
            "major_maintenance_reserve": True,
            "step_in_rights": True,
            "assignment_provisions": True,
            "change_of_control_provisions": True,
        },
        "market": {
            "resource_quality": "good",
            "resource_assessment_confidence": "p50",
            "independent_resource_assessment": False,
            "market_price_per_mwh": 55,
            "market_price_trend": "increasing",
            "curtailment_history_percent": 0.0,
            "interconnection_certainty": "secured",
            "grid_congestion_risk": "moderate",
            "competing_projects_in_queue": 2,
            "community_support": "supportive",
            "land_lease_secured": True,
            "land_lease_term_years": 25,
        },
    },
}


@project_bp.route("/new")
def new_project():
    return render_template(
        "project_input.html",
        technology_types=TECHNOLOGY_TYPES,
        project_stages=PROJECT_STAGES,
        offtake_types=OFFTAKE_TYPES,
        entity_types=ENTITY_TYPES,
        sample_projects=SAMPLE_PROJECTS,
    )


@project_bp.route("/load-sample/<sample_key>")
def load_sample(sample_key):
    sample = SAMPLE_PROJECTS.get(sample_key)
    if not sample:
        flash("Sample project not found.", "error")
        return redirect(url_for("project.new_project"))
    store_set("project_data", sample)
    return redirect(url_for("analysis.results"))


@project_bp.route("/submit", methods=["POST"])
def submit_project():
    """Process the project input form."""
    form = request.form.to_dict(flat=True)

    project_data = {
        "project_name": form.get("project_name", ""),
        "project_id": form.get("project_id", ""),
        "project_stage": form.get("project_stage", "pre_development"),
        "entity_type": form.get("entity_type", "investor_owned_utility"),
        "location_state": form.get("location_state", ""),
        "location_county": form.get("location_county", ""),
        "is_rural": form.get("is_rural", "false"),
        "cod_target": form.get("cod_target", ""),
        "description": form.get("description", ""),
        "technical": {
            "technology_type": form.get("technology_type", "solar_pv"),
            "nameplate_capacity_mw": form.get("nameplate_capacity_mw", "0"),
            "annual_generation_mwh": form.get("annual_generation_mwh", "0"),
            "capacity_factor": form.get("capacity_factor", "0"),
            "technology_readiness_level": form.get("technology_readiness_level", "9"),
            "expected_useful_life_years": form.get("expected_useful_life_years", "30"),
            "degradation_rate_annual": form.get("degradation_rate_annual", "0.005"),
            "availability_factor": form.get("availability_factor", "0.98"),
            "interconnection_voltage_kv": form.get("interconnection_voltage_kv", "0"),
            "interconnection_status": form.get("interconnection_status", "planned"),
            "environmental_permits_secured": form.get("environmental_permits_secured", "false"),
            "site_control_secured": form.get("site_control_secured", "false"),
        },
        "financial": {
            "total_project_cost": form.get("total_project_cost", "0"),
            "total_hard_costs": form.get("total_hard_costs", "0"),
            "total_soft_costs": form.get("total_soft_costs", "0"),
            "contingency_percent": form.get("contingency_percent", "0.10"),
            "construction_period_months": form.get("construction_period_months", "24"),
            "debt_percent": form.get("debt_percent", "0.70"),
            "equity_percent": form.get("equity_percent", "0.30"),
            "interest_rate": form.get("interest_rate", "0.055"),
            "debt_tenor_years": form.get("debt_tenor_years", "20"),
            "target_dscr": form.get("target_dscr", "1.40"),
            "annual_revenue": form.get("annual_revenue", "0"),
            "annual_opex": form.get("annual_opex", "0"),
            "annual_opex_escalation": form.get("annual_opex_escalation", "0.025"),
            "revenue_escalation": form.get("revenue_escalation", "0.02"),
            "tax_rate": form.get("tax_rate", "0.21"),
            "itc_percent": form.get("itc_percent", "0"),
            "ptc_per_mwh": form.get("ptc_per_mwh", "0"),
            "depreciation_schedule": form.get("depreciation_schedule", "macrs_5"),
            "discount_rate": form.get("discount_rate", "0.08"),
        },
        "credit": {
            "offtake_type": form.get("offtake_type", "ppa_fixed"),
            "offtake_tenor_years": form.get("offtake_tenor_years", "20"),
            "offtaker_credit_rating": form.get("offtaker_credit_rating", "BBB"),
            "offtaker_entity_type": form.get("offtaker_entity_type", "investor_owned_utility"),
            "revenue_concentration_percent": form.get("revenue_concentration_percent", "1.0"),
            "regulatory_stability_rating": form.get("regulatory_stability_rating", "stable"),
            "curtailment_risk": form.get("curtailment_risk", "low"),
            "counterparty_count": form.get("counterparty_count", "1"),
            "contract_price_per_mwh": form.get("contract_price_per_mwh", "0"),
            "has_credit_support": form.get("has_credit_support", "false"),
            "credit_support_type": form.get("credit_support_type", ""),
        },
        "structure": {
            "epc_contract_type": form.get("epc_contract_type", "fixed_price_turnkey"),
            "epc_contractor_experience": form.get("epc_contractor_experience", "established"),
            "epc_warranty_years": form.get("epc_warranty_years", "2"),
            "om_contract_type": form.get("om_contract_type", "full_service"),
            "om_contract_tenor_years": form.get("om_contract_tenor_years", "10"),
            "insurance_coverage": form.get("insurance_coverage", "comprehensive"),
            "performance_guarantee": form.get("performance_guarantee", "true"),
            "performance_guarantee_level": form.get("performance_guarantee_level", "0.95"),
            "completion_guarantee": form.get("completion_guarantee", "true"),
            "reserve_accounts_funded": form.get("reserve_accounts_funded", "false"),
            "debt_service_reserve_months": form.get("debt_service_reserve_months", "6"),
            "major_maintenance_reserve": form.get("major_maintenance_reserve", "false"),
            "step_in_rights": form.get("step_in_rights", "true"),
            "assignment_provisions": form.get("assignment_provisions", "true"),
            "change_of_control_provisions": form.get("change_of_control_provisions", "true"),
        },
        "market": {
            "resource_quality": form.get("resource_quality", "good"),
            "resource_assessment_confidence": form.get("resource_assessment_confidence", "p50"),
            "independent_resource_assessment": form.get("independent_resource_assessment", "false"),
            "market_price_per_mwh": form.get("market_price_per_mwh", "0"),
            "market_price_trend": form.get("market_price_trend", "stable"),
            "curtailment_history_percent": form.get("curtailment_history_percent", "0"),
            "interconnection_certainty": form.get("interconnection_certainty", "high"),
            "grid_congestion_risk": form.get("grid_congestion_risk", "low"),
            "competing_projects_in_queue": form.get("competing_projects_in_queue", "0"),
            "community_support": form.get("community_support", "supportive"),
            "land_lease_secured": form.get("land_lease_secured", "false"),
            "land_lease_term_years": form.get("land_lease_term_years", "30"),
        },
    }

    project_data = coerce_numeric_fields(project_data)

    errors = validate_project_input(project_data)
    if errors:
        for error in errors:
            flash(error, "error")
        return redirect(url_for("project.new_project"))

    store_set("project_data", project_data)
    return redirect(url_for("analysis.results"))
